# Generated by Django 6.0.5 on 2026-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imatge_alter_author_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='tags/'),
        ),
    ]
